{% set version = "1.0.3" %}

package:
  name: spago
  version: {{ version }}

source:
  url: https://registry.npmjs.org/spago/-/spago-{{ version }}.tgz
  sha256: c19564dfd1653baf6d458e3727c8849d4ab4b0ab321bd3fa4608058f3c1e9256

build:
  number: 0
  skip: true  # [win or ppc64le]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make
    - nodejs
    - pnpm
    - pnpm-licenses
  host:
    - nodejs
  run:
    - nodejs

test:
  commands:
    - spago --help

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: PureScript package manager and build tool
  home: https://github.com/purescript/spago
  dev_url: https://github.com/purescript/spago

extra:
  recipe-maintainers:
    - danielnachun
