{% set version = "1.0.2" %}

package:
  name: spago
  version: {{ version }}

source:
  url: https://registry.npmjs.org/spago/-/spago-{{ version }}.tgz
  sha256: 23a1d8ce5857865843f0f2ca1ee756c0b1f79350ca86396f5ced949b951302ad

build:
  number: 0
  skip: true  # [win or ppc64le]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make
    - nodejs
    - pnpm
    - pnpm-licenses
  host:
    - nodejs
  run:
    - nodejs

test:
  commands:
    - spago --help

about:
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: PureScript package manager and build tool
  home: https://github.com/purescript/spago
  dev_url: https://github.com/purescript/spago

extra:
  recipe-maintainers:
    - danielnachun
